### ISSUE TITLE
I love Slicksters Github Build crashes at startup at current Spaced Out! build.

### ISSUE THREAD

**Issue by Kreygasm13** [Pholith/ONI-Mods#10]
**Describe the bug**
Crashing at startup.

**To Reproduce**
Enable the mod and restart the game.

**Output_log.txt**
[Player.log](https://github.com/Pholith/ONI-Mods/files/6609322/Player.log)

**Screenshots**
If needed, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language Version 20H2
 - Mine the Gap Update
 
**Additional context**

**Comment by Pholith** [comment]
Yeah, compatibility with the new merged version is WIP.

**Comment by Pholith** [comment]
I Love Slicksters is now compatible
