### ISSUE TITLE
[Mod suggestion] Cable mod

### ISSUE THREAD

**Issue by 32bitx64bit** [Pholith/ONI-Mods#23]
Hi, I've only found one cable mod for ONI but its out of date and the author said he didn't play much ONI and wasn't going to update his mod(s).

So I feel like a cable mod for ONI would be nice (Considering there is none)

Link to his Gigawatt wire mod
https://github.com/egladil/oni-mods/tree/master/GigawattWire
(Under MIT license)

**Comment by Pholith** [comment]
Hi, really sorry for the time. I'm okay to help to maintains mods but would like to non-duplicate mods on steam. If the author is okay I can update mods on the actuel steam page (with steam permissions)

**Comment by Pholith** [comment]
I took the maintenance of the GigaWatt Wire mod from Egladil, the new mod is available here: https://steamcommunity.com/sharedfiles/filedetails/?id=3096204182

**Comment by 32bitx64bit** [comment]
> I took the maintenance of the GigaWatt Wire mod from Egladil, the new mod is available here: https://steamcommunity.com/sharedfiles/filedetails/?id=3096204182

Just returned to the game recently and saw this!
Cheers for supporting it once again
