### ISSUE TITLE
Polluted Electrolyzer prompts error window on game startup

### ISSUE THREAD

**Issue by Thundercraft** [Pholith/ONI-Mods#25]
**Describe the bug**
After subscribing to Polluted Electrolyzer, enabling it in-game and restarting, I get the error on startup: "Oops-a-daisy! We're sorry, but it seems your game has encountered an error." And a window pops up with my mods, but with Polluted Electrolyzer in red and automatically disabled due to the error.

**To Reproduce**
1. Subscribe to mod on Steam Workshop.
2. After starting ONI, go to the mod menu and check the checkbox next to Polluted Electrolyzer to enable it.
3. On exiting the mod menu, a popup window will prompt to restart the game. Do so.
4. On game restart, the aforementioned error will appear.

**Output_log.txt**
[Player.log](https://github.com/Pholith/ONI-Mods/files/11367652/Player.log)

**Screenshots**
![Polluted Electrolyzer crash on startup](https://user-images.githubusercontent.com/6333849/235516385-e82f490f-b463-4691-a28c-46ec951b20c9.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version: Build: U46-552078 (with Spaced Out DLC)

**Additional context**
While I really wanted to use your "Polluted Electrolyzer" mod, I found it was currently in a completely un-usable state. After subscribing to the mod, I did NOT get any warning like "incompatible with" current version or even "not compatible with Spaced Out". Rather, it was only after putting the checkbox next to this mod to enable it and restarting that I got the message, "Oops-a-daisy! We're sorry, but it seems your game has encountered an error." And I only hand about 3 other mods enabled at the time - a mod manager + 2 bugfix mods.

**Comment by Pholith** [comment]
Really sorry for the time, I forgot about it but I finnaly fixed the mod
