### ISSUE TITLE
Wall Pumps - Fixed Translation

### ISSUE THREAD

**Issue by DarkEviL88** [Pholith/ONI-Mods#27]
I did the translation, but the settings menu is not translated, although there are strings from the settings menu in the template.
[ru.zip](https://github.com/Pholith/ONI-Mods/files/13742210/ru.zip)

**Comment by Pholith** [comment]
Thanks, I uploaded it.
I also take a look at option localization, I tried to fix that but couln't end it for the moment

**Comment by DarkEviL88** [comment]
![image](https://github.com/Pholith/ONI-Mods/assets/50534207/9921f96a-1f47-4c1c-9f45-bfa9f720fbc0)
After updating the mod, the High pressure gas wall vent translation stopped working.
![image](https://github.com/Pholith/ONI-Mods/assets/50534207/8e61a12e-6a2d-4975-aa3f-f9c25b2f4143).
I figured out why the translation stopped working, you changed the strings in the template.
I'll wait until you've finished the mod to translate it again.

**Comment by Pholith** [comment]
Oh okay yes I had problems with this one and I changed his name.
I will change it too in your ru.po you don't need to do it again. Except if you have string corrections to put at the same time.

I'll fix option strings early january, I don't have the time right now sorry

**Comment by DarkEviL88** [comment]
ok

**Comment by DarkEviL88** [comment]
Sorry if I'm being too intrusive, but the High pressure gas wall vent is still in English as is the settings menu. Here is a new .po file with which High pressure gas wall vent is translated into Russian.
[ru.zip](https://github.com/Pholith/ONI-Mods/files/13851832/ru.zip)
![image](https://github.com/Pholith/ONI-Mods/assets/50534207/a5b145ac-7eef-440c-a863-aa0699540389)
I realize you may not have enough free time to edit the mod. Take your time. Thank you.

**Comment by Pholith** [comment]
Hi, thanks, yes I not have a lot of free time right now. But my main problem is I have difficulties to solve the strings staying in english. I'm on it, and maybe I will change again the translation template file to solve it (.pot)

**Comment by DarkEviL88** [comment]
Hey, take your time. It's not a problem, I will make a new translation file and provide it to you.

**Comment by Pholith** [comment]
I finally succed to make it work, it's on steam. Can you double check it's also good in russian pls ? @DarkEviL88

**Comment by DarkEviL88** [comment]
![image](https://github.com/Pholith/ONI-Mods/assets/50534207/d87fda99-c78a-4141-a707-aedbcdcb61b6)
![image](https://github.com/Pholith/ONI-Mods/assets/50534207/4ef99f89-f01a-44c4-afc9-b636729f81ef)
![image](https://github.com/Pholith/ONI-Mods/assets/50534207/dbcb41ae-c1bb-4d82-a2f1-380958a34828)
Yes, everything works perfectly, thank you very much!

**Comment by Pholith** [comment]
Thanks
