### ISSUE TITLE
Solar System Worlds+EmptyWorlds - Translation

### ISSUE THREAD

**Issue by DarkEviL88** [Pholith/ONI-Mods#29]
I wrote to you on Steam about the translation not working, I provide you with my translation files, maybe I did something wrong.

[Solar System Worlds 1930918856 RU.zip](https://github.com/Pholith/ONI-Mods/files/14298808/Solar.System.Worlds.1930918856.RU.zip)

[EmptyWorlds (SkyBlock) 1825146346 RU.zip](https://github.com/Pholith/ONI-Mods/files/14298810/EmptyWorlds.SkyBlock.1825146346.RU.zip)

**Comment by Pholith** [comment]
The files are good, there is actually a problem in the mod translation. I fixed SolarSystemWorlds and uploaded it. I'm on Emptyworlds now

**Comment by Pholith** [comment]
Empty Worlds is updated too, thanks!

**Comment by DarkEviL88** [comment]
Thank you!
