### ISSUE TITLE
I Love Slicksters - Morphs !

### ISSUE THREAD

**Issue by Tellik** [Pholith/ONI-Mods#3]
Only mod loaded, causes error on loading the game initially and getting to the title screen. Mod is automatically disabled before main menu.

https://pastebin.com/7DLCDtYB

This occurred with both the local dev build I downloaded previously and the latest steam provided version.

**Comment by Pholith** [comment]
this has already been fixed 6 days ago and uploaded to Steam 2 days ago.
Please do not create unnecessary issues....

**Comment by Tellik** [comment]
My apologies. It seems like it was just an issue with steam then, since the github version is working correctly. (I don't always have a chance to download the newest version which is why it takes me a bit longer to test some things.)

As it is right now, Steam is still distributing the broken version for me.
