### ISSUE TITLE
[BUG] ILoveSlickster crash with More Plants enabled

### ISSUE THREAD

**Issue by fruixs** [Pholith/ONI-Mods#33]
#### Describe the bug
it crashes on launching game after enable ILoveSlickster and restart game

#### Steps To Reproduce
1. Enable ILoveSlickster
2. Restart
3. Crash on launching game

#### Mod Version
- Vanilla, Spaced Out, Frosty Planet
- v2.0.5

#### my all active mods list
Here this mod profile for your easy debugging
[ONI MPM Recommended v18.json](https://github.com/user-attachments/files/16356715/ONI.MPM.Recommended.v18.json)

 - Mod Updater
 - Mod Profile Manager
 - Mod Preset Manager [MPM]
 - Stock Bug Fix
 - Always Show Capacity
 - Neutronium Cave
 - Demolish Neutronium
 - Skill Queue
 - Skills Retainer
 - 传送服 Teleport Suit
 - Rebalanced Plant Mutations
 - Eat every day
 - No Critter Overcrowding
 - AI Improvements
 - Extra Moulding Skins
 - Food Supply Tooltip
 - Critter Shedding
 - Efficient Supply
 - Auto Light Tile(自亮砖)
 - Capsule 2.0
 - Waste Not, Want Not
 - Where's My Loot?
 - MegaBattery
 - Smoother Light (Vanilla/DLC)
 - Stats Unlimited
 - [DLC] Radiation Rebalanced
 - Endless Science
 - No Manual Delivery
 - Configurable Automation-controlled Doors
 - Planning Tool
 - Blood
 - Sick Go To Med Bed
 - Automation Bypass
 - [Vanilla + DLC] Symbiotic Germs
 - Block Decor Effects Behind Walls
 - Passive Gas Vent Input
 - Plastic Utilities
 - Butcher & Fishing Stations
 - Falling Sand
 - Wounded Go To Med Bed
 - Steel Ladder
 - Sweep By Type
 - Deselect New Materials
 - No Drop // by @Ony 
 - Duplicant Stat Selector [DSS]
 - Fragrant Flowers
 - Plastic Mesh and Airflow Tiles
 - Research Queue
 - Enclosed Telescope Tune-Up
 - Space POI Additional Info
 - Gigawatt Wire
 - Pip Plant Overlay
 - Endless Telescope
 - Big Storage
 - Utility Glass
 - Smelter
 - Wall Pumps
 - Control your Robots
 - [Vanilla + DLC] Biobot Upgrades
 - ConveyorTiles
 - Debris Thermostat 碎片恒温器
 - Universal Electrolyzer
 - Gassy Moo Eat Flowers
 - Buildable Natural Tile
 - Advanced Flow Management
 - Automated Canisters Reloaded
 - Auto Suit Delivery
 - Pick up Flopping Pacu
 - Shinebug Reactor
 - 主动洗手 Active Hand Washing
 - Portal Network
 - Dupes Logistics
 - [Vanilla + DLC] More Logic Ports
 - Cluster Generation Manager [CGM]
 - Wrangle & Carry
 - "Move Here" Command Tile
 - Bio-Inks: Rechargeable Printing Pods
 - Balloon Dispenser
 - Simpler Pip Plant Rule (Vanilla/DLC)
 - Fixed Ore Scrubber
 - Happy Digging: Dwarf Edition (Fixed)
 - Aquatic Farm
 - Buildable Neural Vacillator
 - Scan & Relay Satellites
 - Configurable Timers
 - Dupes Machinery
 - Dupes Engineering
 - Trash Cans
 - Move This Here
 - Daily Routine
 - Rocketry Expanded
 - Canned Food
 - [Vanilla + DLC] Diseases Expanded
 - Crabs Profit
 - Freezer
 - Carousel
 - Auto Remove Baby
 - HVAC Expansion
 - Worn Suit doesn't drop Canister
 - Better Info Cards
 - Better Farming Effects and Tweaks
 - Packaged Bleach Stone
 - More Plants
 - Space Radiator
 - Custom Reservoirs
 - Sealed and Insulated Containers
 - Queue For Sinks
 - Sealed Pitcher Pump
 - Build Over Plants (식물 위에 건설)
 - Bubbles Bathtub
 - Plastic Door
 - Self-sealing Airlocks Revived
 - Workshop Profiles
 - True Tiles
 - Custom Generators
 - Hysteresis Storage
 - Rest for the Weary
 - Laser Turret (Vanilla/DLC)
 - Grind Up Metals
 - Insulated Radbolt Joint Plate
 - Weeb Dupes
 - Tiny Door
 - Clothing Locker
 - Squirrel Wheel
 - Improved World Traits [UPDATED]
 - Dupes Refrigeration
 - Insulated Joint Plate
 - Insulated Door
 - Ribbed Fire Pole
 - Decor Pack I
 - Movable Features 位移信标
 - Show Building Ranges
 - More Small Sculptures
 - More Marble Sculptures
 - Wild Planter Box
 - Smart Pumps
 - EthanolGeyser
 - Empty Worlds
 - Giant Doors
 - 传送端口 (Transfer Port)
 - Extended Building Width
 - Geysers Automation Extension 间歇泉自动化扩展
 - More Emotions
 - Critter Inventory
 - Space Store 太空商店
 - [Vanilla + DLC] Rooms Expanded
 - Mechanics Station
 - AI Controlled Rockets
 - 自然种植盒（Natural Plant Box）
 - DuperyFixed
 - NSHS MOD For Dupery
 - Smart Coolers
 - MedicineExpanded
 - Group Favorite Resources
 - MutationFarmer
 - Athletic Manual Generator
 - Any Ice Liquefier
 - Space Store Expansion Pack
 - Critter Traits
 - Only Tame
 - Build Priority Keys
 - EthanolGeyser
 - Overjoy Chance Rebalanced
 - Artifacts in Care Packages
 - Vitals Display Rads
 - One Giant Leap
 - Help, none of my mod options are working after the DLC update - fix

#### Game logs

[Player.log](https://github.com/user-attachments/files/16356646/Player.log)

```
Error in GameAssets(Clone).Assets.OnPrefabInit at (0.0, 0.0, 0.0)

System.NullReferenceException: Object reference not set to an instance of an object
  at EntityTemplates.ExtendEntityToBeingABaby (UnityEngine.GameObject prefab, Tag adult_prefab_id, System.String on_grow_item_drop_id, System.Boolean force_adult_nav_type, System.Single adult_threshold) [0x00062] in <ac8788b5d0fb4b89a20068ab3b6a25de>:0 
  at ILoveSlicksters.AquaOilfloaterBabyConfig.CreatePrefab () [0x0002f] in <23f87f1b3a624386973175f3dcda80e7>:0 
  at EntityConfigManager.RegisterEntity (IEntityConfig config) [0x00000] in <ac8788b5d0fb4b89a20068ab3b6a25de>:0 
  at (wrapper dynamic-method) EntityConfigManager.EntityConfigManager.LoadGeneratedEntities_Patch3(EntityConfigManager,System.Collections.Generic.List`1<System.Type>)
  at LegacyModMain.LoadEntities (System.Collections.Generic.List`1[T] types) [0x00000] in <ac8788b5d0fb4b89a20068ab3b6a25de>:0 
  at LegacyModMain.Load () [0x0004d] in <ac8788b5d0fb4b89a20068ab3b6a25de>:0 
  at Assets.CreatePrefabs () [0x00055] in <ac8788b5d0fb4b89a20068ab3b6a25de>:0 
  at (wrapper dynamic-method) Assets.Assets.OnPrefabInit_Patch15(Assets)
  at KMonoBehaviour.InitializeComponent () [0x00068] in <3cae53dcd334432a8d9641184e90df7c>:0 
Build: U52-623230-SC
```

#### Screenshot
If it is something else then a crash, add screenshots to help explain your problem.

**Comment by Pholith** [comment]
Can you try with More plants disabled ? Some people reported me an incompatibility with this mod

**Comment by fruixs** [comment]
Yes, I Love Slickster enabled and More plants disabled then No Error on loading

**Comment by Pholith** [comment]
So it is an incompatibility due to the More plants mod I close this.
