### ISSUE TITLE
Thanks for your "NotePad"

### ISSUE THREAD

**Issue by Eglusaxie** [Pholith/ONI-Mods#5]
I originally wanted to refer to your code, but I found that you seem to have finished what I want to do, which is your "NotePad".

**Comment by Eglusaxie** [comment]
Hahaha now I don't need to make this mod myself, thank you very much.
(^v^)

**Comment by Eglusaxie** [comment]
I don't know much about C#,I thought it must will take me a lot of time, Now I really got a surprise lol.

**Comment by Pholith** [comment]
Hi, My notepad mod is still in working, I think I'll be able to release it in a few days.
