### ISSUE TITLE
Notepad conflicts with DraggableUI

### ISSUE THREAD

**Issue by EtiamNullam** [Pholith/ONI-Mods#7]
Looks like there is a conflict between mod `Notepad` and my mod `DraggableUI`.

At first it was not working at all but when `DraggableUI` comes after `Notepad` in mod order my mod reported error on my end that I easily fixed. Sadly its still crashing without notice when `Notepad` comes after `DraggableUI` in mod order. My mod makes every UI draggable so it probably conflicts with you adding some custom UI.

Its probably a matter of maybe adding a few checks for null or something like that. I bet there is some exception thrown but you're not logging it.

Related issue on my repo: https://github.com/EtiamNullam/Etiam-ONI-Modpack/issues/6

**Comment by Pholith** [comment]
@EtiamNullam 
I tried to reproduce the bug with the 2 mods activated (the steam versions) and I didn't manage to reproduce it, whatever the order the mods are in. I thought I saw in your notes a fix , is this bug still current?

**Comment by EtiamNullam** [comment]
@Pholith 
Hmm, did you fix it? There was an update for `Notepad` when I launched the game.

The fix I made previously on my end was working only when my mod came last in the mod order.

Either way I just tested and it works for me right now, no matter the order.

**Comment by Pholith** [comment]
I didn't change anything in the code last update, I just added a translation I was asked for here. 
Great, I'm glad that this bug solved itself 😄

**Comment by EtiamNullam** [comment]
Interesting. Lets hope it won't come back again the way it disappeared :D
