### ISSUE TITLE
Notepad：It crashes the game when i click elsewhere after typing. 

### ISSUE THREAD

**Issue by Eglusaxie** [Pholith/ONI-Mods#9]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Output_log.txt**
Add the output_log.txt file.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - Version of the game [e.g. Recreation Upgrade or [Game Update] -  381818]

**Additional context**

**Comment by Pholith** [comment]
Seams to be fixed with recent version of PLib
